name: Deploy Test API

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: [self-hosted, self-hosted-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check the current user
        run: |
          whoami

      - name: Build Test API Docker image
        run: |
          docker build -t natinael/todo-backend .

      - name: Login to Docker registry
        run: |
         docker login ${{secrets.registry}} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}    

      - name: Tag the image
        run: |
          docker tag natinael/todo-backend:latest ${{secrets.DOCKER_IMAGE}}

      - name: Push Docker image
        run: |
          docker push ${{secrets.DOCKER_IMAGE}}

      - name: import the ansible file
        run: |
            aws s3 cp s3://prom-container-monitoring/ansible-yaml /home/ec2-user/ --recursive
            aws s3 cp s3://prom-container-monitoring/inventory.txt /home/ec2-user/ --recursive

      - name: Run Ansible PlayBook
        run: |
          cd /home/ec2-user && ansible-playbook -i inventory.txt backend-ansible.yaml

      - name: Run Ansible PlayBook For monitoring
        run: |
          cd /home/ec2-user && ansible-playbook -i inventory.txt prometheus-ansible.yaml
      
      - name: Run Ansible PlayBook For deployment
        run: |
          cd /home/ec2-user && ansible-playbook -i inventory.txt exporters-for-deploments.yaml
              
      - name: delete file
        run: 
            sudo rm /home/ec2-user/*.yaml /home/ec2-user/*.txt

